name: Download

on: push

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download mctl release
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "aranajhonny/test"
          latest: true
          fileName: "*"
          token: ${{ secrets.GITHUB }}

      - name: Install mctl
        run: |
          unzip -d mctl "$(find . -name 'mctl-*-linux-x86.zip' -print -quit)"
          mv mctl/mctl /usr/local/bin/mctl

      - name: Create config.
        env:
          MCTL_TOKEN: ${{ secrets.MCTL_TOKEN }}
        run: bash config.sh

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Run tests
        uses: actions-rs/cargo@v1
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          command: run
          args: --release
